name             'mysql-bench'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures mysql-bench'
long_description 'Installs/Configures mysql-bench'
version          '0.1.0'
depends          'build-essential'
depends          'database'
